import type { Metadata } from 'next';
//import { Inter as FontSans } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { Maven_Pro as FontSans } from 'next/font/google';

const maven = FontSans({
  weight: '400',
  subsets: ['latin'],
});

import '../styles/globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Template',
  description: 'Generated by nodup tecnologia',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='pt'>
      <body
        className={cn('min-h-screen bg-slate-100 antialiased', maven.className)}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
